#Specify Redis Server configuration here
redis:
  development:
    host: '10.106.50.73'
    port: 6379
  test:
    host: localhost
    port: 6379
  production:
    host: localhost
    port: 6379

#Specify the Model to be used by Chatter, defaults to User
chatter:
  model: Provider
  key: qwerty97531